[tool.poetry]
name = "training"
version = "0.1.0"
description = ""
authors = ["Claudio Di Blasi <cdib@bendingspoons.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
